connector_image: airbyte/source-YOUR_PACKAGE:dev
test_strictness_level: low

acceptance_tests:
  spec:
    tests:
      - spec_path: "YOUR_PACKAGE/spec.yaml"
  
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
  
  discovery:
    tests:
      - config_path: "secrets/config.json"
  
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        expect_records:
          path: "integration_tests/expected_records.jsonl"
  
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
  
  incremental:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
